### ISSUE TITLE
Eclipse UpdateSite

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/galen_ide#13]

**Comment by s3dse** [comment]
Introduced a working p2 update site. 
New modules are:
`com.galenframework.specs.feature`
`com.galenframework.specs.update`
Ready for verification.

**Comment by hypery2k** [comment]
Getting the following error when trying to use the UpdateSite:
```
Could not find https://martinreinhardt-online.de/update_sites/galen_ide/nightly/
```
See the pipeline:
https://martinreinhardt-online.de/jenkins/view/GalenFramework/job/Galen_IDE_build/
The Update is available here:
https://martinreinhardt-online.de/update_sites/galen_ide/nightly/

**Comment by s3dse** [comment]
I think your URL misses something. The update site is located under
`https://martinreinhardt-online.de/update_sites/galen_ide/nightly/repository`.
This location works for me.

**Comment by hypery2k** [comment]
cool ;)
