### ISSUE TITLE
Support IntelliJ 2016.2

### ISSUE THREAD

**Issue by hoomb** [hypery2k/galen_ide#14]
Please add support for recent IntelliJ 2016.2, Thank you.

**Comment by hypery2k** [comment]
I will take a look at it. I'm currently on holiday and so away from my computer. I'll try to make an 
Preview

**Comment by hoomb** [comment]
Hello, any progress on this?

**Comment by hypery2k** [comment]
sorry, but currently not having time for this project

**Comment by hypery2k** [comment]
should be resolved in 0.2.0
